public enum PrivacyFilter {
    static let blockedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    public static func shouldStore(pasteboardTypes: Set<String>) -> Bool {
        pasteboardTypes.isDisjoint(with: blockedTypes)
    }
}
